spring.application.name=BillingPlatformApplication
spring.profiles.active=dev
server.port=8081

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized

logging.level.root=INFO
logging.level.com.billingplatformapplication=DEBUG

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.packages-to-scan=com.billingplatformapplication
springdoc.paths-to-match=/api/**